on: push
jobs:
  build-nodemcuv2:
    name: Build binary for nodemcuv2
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.10'
      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1
        with:
          platformio-version: "6.1.6"
      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0 # npm dependency resolution for esp8266 iot framework breaks with 16
      - name: Build PlatformIO project
        run: pio run -d ./ -e nodemcuv2
      - name: Adjust firmware filename
        run: mv .pio/build/nodemcuv2/firmware.bin firmware-nodemcuv2.bin
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: firmware-nodemcuv2.bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-d1:
    name: Build binary for d1
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1
        with:
          platformio-version: "6.1.6"
      - uses: actions/setup-node@v3
        with:
          node-version: 14.3.0 # npm dependency resolution for esp8266 iot framework breaks with 16
      - name: Build PlatformIO project
        run: pio run -d ./ -e d1
      - name: Adjust firmware filename
        run: mv .pio/build/d1/firmware.bin firmware-d1.bin
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: firmware-d1.bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-d1_mini:
    name: Build binary for d1_mini
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1
        with:
          platformio-version: "6.1.6"
      - uses: actions/setup-node@v3
        with:
          node-version: 14.3.0 # npm dependency resolution for esp8266 iot framework breaks with 16
      - name: Build PlatformIO project
        run: pio run -d ./ -e d1_mini
      - name: Adjust firmware filename
        run: mv .pio/build/d1_mini/firmware.bin firmware-d1_mini.bin
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: firmware-d1_mini.bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
